#include "./include/project.h"

#define PANEL1_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB28  //tranzystor Q3 odaplony
#define PANEL1_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB28  //Tranzystor Q3 zgaszony

#define PANEL2_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB30  //tranzystor Q2 odaplony
#define PANEL2_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB30  //Tranzystor Q2 zgaszony

#define SEG_A_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB25
#define SEG_B_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB24
#define SEG_C_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB22
#define SEG_D_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB21
#define SEG_E_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB20
#define SEG_F_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB27
#define SEG_G_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB26
#define SEG_KR_ON AT91C_BASE_PIOB->PIO_CODR = AT91C_PIO_PB23


#define SEG_A_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB25
#define SEG_B_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB24
#define SEG_C_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB22
#define SEG_D_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB21
#define SEG_E_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB20
#define SEG_F_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB27
#define SEG_G_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB26
#define SEG_KR_OFF AT91C_BASE_PIOB->PIO_SODR = AT91C_PIO_PB23


void dbgu_print_ascii (const char *buffer)
{

}

int main(void)
{
  PANEL1_ON;
  SEG_A_ON;
  SEG_G_ON;
  SEG_D_ON;
  PANEL1_OFF;
  
  PANEL2_ON;
  SEG_F_ON;
  SEG_C_ON;
  PANEL2_OFF;

  return 0;
}
